AUTH:
  AUTO_LOGIN:
    ENABLED: true
    TIMEOUT_SECONDS: 86400      # How long auto login stays valid after last login (1 hour)
    CHECK_IP: true             # Verify IP matches for auto-login (adds some security)
  PASSWORD:
    MIN_LENGTH: 6             # Minimum password length
    MAX_LENGTH: 32            # Maximum password length
    HASH_ALGORITHM: "SHA-256"
  LOGIN:
    MAX_ATTEMPTS: 5           # Max wrong attempts before temp lockout
    LOCKOUT_TIME_SECONDS: 300 # Time user is locked out after max attempts (5 minutes)
    KICK_IF_NOT_LOGGED_IN_SECONDS: 60 # Time allowed before kicking unauthed player